from models import School, User, Competition, db
from app import app

# Create all tables
db.drop_all()
db.create_all()

School.query.delete()
User.query.delete()
Competition.query.delete()

# Make a bunch of schools ()
tamu = School(school_code="tamu", city="College Station", school_name="Texas A&M University")
uh = School(school_code="uh", city="Houston", school_name="University Houston")
unt = School(school_code="unt", city="Denton", school_name="University of North Texas")
uta = School(school_code="uta", city="Arlington", school_name="University of Texas at Arlington")
ut = School(school_code="ut", city="Austin", school_name="University of Texas at Austin")
utd = School(school_code="utd", city="Dallas", school_name="University of Texas at Dallas")
utep = School(school_code="utep", city="El Paso", school_name="University of Texas at El Paso") 
utrgv = School(school_code="utrgv", city="Edinburg", school_name="University of Texas, Rio Grande Valley")
utsa = School(school_code="utsa", city="San Antonio", school_name="University of Texas at San Antonio")

db.session.add_all([tamu, uh, unt, uta, ut, utd, utep, utrgv, utsa])
db.session.commit()

# Make a bunch of users (first_name, last_name, email, school_code)
agatha = User.register(first_name="Agatha", last_name="Harkness", gender="Female", school_code="tamu", email="agatha@agatha.edu", password="password")
alistair = User.register(first_name="Alistair", last_name="Fitz", gender="Male", school_code="ut", email="alistair@hydra.com", password="password")
alphonso = User.register(first_name="Alphonso", last_name="Mackenzie", gender="Male", school_code="uh", email="bigmack@avengers.edu", password="password")
andrew = User.register(first_name="Andrew", last_name="Garner", gender="Male", school_code="utsa", email="beastmode@shield.edu", password="password")
bobbi = User.register(first_name="Bobbi", last_name="Morse", gender="Female", email="bobbi@shield.edu", school_code="uh", password="password")
bruce = User.register(first_name="Bruce", last_name="Banner", gender="Male", email="bruce@bruce.edu", school_code="uh", password="password")
bucky = User.register(first_name="Bucky", last_name="Barnes", gender="Male", email="white_wolf@avengers.edu", school_code="unt", password="password")
carol = User.register(first_name="Carol", last_name="Danvers", gender="Female", email="capt_marvel@email.com", school_code="uta", password="password")
cassandra = User.register(first_name="Cassandra", last_name="Lang", gender="Female", email="ant_daughter@shield.edu", school_code="ut", password="password")
daisy = User.register(first_name="Daisy", last_name="Johnson", gender="Female", email="daisy@shield.edu", school_code="ut", password="password")
daniel = User.register(first_name="Daniel", last_name="Susa", gender="Male", email="daniel@shield.edu", school_code="ut", password="password")
d_whitehall = User.register(first_name="Daniel", last_name="Whitehall", gender="Male", email="whitehall@hydra.com", school_code="uh", password="password")
darren = User.register(first_name="Darren", last_name="Cross", gender="Male", email="darren@hydra.com", school_code="tamu", password="password")
deke = User.register(first_name="Deke", last_name="Shaw", gender="Male", email="spaceboy@shield.edu", school_code="ut", password="password")
elena = User.register(first_name="Elena", last_name="Rodriguez", gender="Female", email="yoyo@avengers.edu", school_code="unt", password="password")
gideon = User.register(first_name="Gideon", last_name="Malik", gender="Male", email="gideon@hydra.com", school_code="utsa", password="password")
glenn = User.register(first_name="Glenn", last_name="Talbot", gender="Male", email="col_talbot@shield.edu", school_code="utd", password="password")
grant = User.register(first_name="Grant", last_name="Ward", gender="Male", email="hive@hydra.com", school_code="uta", password="password")
henry = User.register(first_name="Henry", last_name="Pym", gender="Male", email="henry@pymlabs.com", school_code="utep", password="password")
holden = User.register(first_name="Holden", last_name="Radcliff", gender="Male", email="dr_radcliff@shield.edu", school_code="utd", password="password")
hope = User.register(first_name="Hope", last_name="Pym", gender="Female", email="hope@pymlabs.com", school_code="utep", password="password")
howard = User.register(first_name="Howard", last_name="Stark", gender="Male", email="howard@stark.com", school_code="ut", password="password")
james = User.register(first_name="James", last_name="Rhodes", gender="Male", email="war_machine@stark.com", school_code="utsa", password="password")
jane = User.register(first_name="Jane", last_name="Foster", gender="Female", email="jane_foster@email.com", school_code="utd", password="password")
jasper = User.register(first_name="Jasper", last_name="Sitwell", gender="Male", email="jasper@hydra.com", school_code="utsa", password="password")
jemma = User.register(first_name="Jemma", last_name="Simmons", gender="Female", email="jemma@shield.edu", school_code="utrgv", password="password")
john = User.register(first_name="John", last_name="Garrett", gender="Male", email="john@hydra.com", school_code="utrgv", password="password")
kamala = User.register(first_name="Kamala", last_name="Khan", gender="Female", email="ms_marvel@avengers.edu", school_code="utsa", password="password")
lance = User.register(first_name="Lance", last_name="Hunger", gender="Male", email="lance@shield.edu", school_code="uta", password="password")
leo = User.register(first_name="Leo", last_name="Fitz", gender="Male", email="fitz_leo@avengers.edu", school_code="uh", password="password")
lincoln = User.register(first_name="Lincoln", last_name="Campbell", gender="Male", email="lincoln@shield.edu", school_code="ut", password="password")
lucy = User.register(first_name="Lucy", last_name="Bauer", gender="Female", email="lucy@bauer.com", school_code="tamu", password="password")
maria = User.register(first_name="Maria", last_name="Hill", gender="Female", email="maria_hill@shield.edu", school_code="tamu", password="password")
melinda = User.register(first_name="Melinda", last_name="May", gender="Female", email="may@avengers@edu", school_code="unt", password="password")
natasha = User.register(first_name="Natasha", last_name="Romanoff", gender="Female", email="natasha@avengers.edu", school_code="uh", password="password")
nathanial = User.register(first_name="Nathanial", last_name="Malik", gender="Male", email="nathan@hydra.com", school_code="utrgv", password="password")
nick = User.register(first_name="Nick", last_name="Fury", gender="Male", email="fury@shield.edu", school_code="unt", password="password")
peggy = User.register(first_name="Peggy", last_name="Carter", gender="Female", email="pcarter@shield.edu", school_code="uta", password="password")
pepper = User.register(first_name="Pepper", last_name="Potts", gender="Female", email="pepper@stark.com", school_code="utrgv", password="password")
peter = User.register(first_name="Peter", last_name="Parker", gender="Male", email="peter@parker.edu", school_code="ut", password="password")
phil = User.register(first_name="Phil", last_name="Coulson", gender="Male", email="phil_coulson@shield.edu", school_code="utd", password="password")
robbie = User.register(first_name="Robbie", last_name="Reyes", gender="Male", email="ghost_rider@shield.edu", school_code="utd", password="password")
rosalind = User.register(first_name="Rosalind", last_name="Price", gender="Female", email="r.price@hydra.com", school_code="uta", password="password")
ruby = User.register(first_name="Ruby", last_name="Hale", gender="Female", email="ruby_hale@hydra.com", school_code="utrgv", password="password")
samual = User.register(first_name="Samuel", last_name="Wilson", gender="Male", email="falcon@avengers.com", school_code="ut", password="password")
scott = User.register(first_name="Scott", last_name="Lang", gender="Male", email="ant_man@avengers.edu", school_code="utep", password="password")
sharon = User.register(first_name="Sharon", last_name="Carter", gender="Female", email="sharon@sharon.edu", school_code="utsa", password="password")
stan = User.register(first_name="Stan", last_name="Lee", gender="Male", email="stan.lee@marvel.com", school_code="utd", password="password")
steve = User.register(first_name="Steve", last_name="Rogers", gender="Male", email="capt_america@avengers.edu", school_code="tamu", password="password")
sunil = User.register(first_name="Sunil", last_name="Bakshi", gender="Male", email="sunail_bakshi@hydra.com", school_code="uh", password="password")
tony = User.register(first_name="Tony", last_name="Starks", gender="Male", email="ironman@stark.com", school_code="unt", password="password")
victoria = User.register(first_name="Victoria", last_name="Price", gender="Female", email="v.price@hydra.com", school_code="tamu", password="password")
wanda = User.register(first_name="Wanda", last_name="Maximoff", gender="Female", email="scarletwitch@vision.com", school_code="uta", password="password")

db.session.add_all([agatha, alistair, alphonso, andrew, bobbi, bruce, bucky, carol, cassandra, daisy, daniel, d_whitehall, darren, deke, elena, gideon, glenn, grant, henry, holden, hope, howard, james, jane, jasper, jemma, john, kamala, lance, leo, lincoln, lucy, maria, melinda, natasha, nathanial, nick, peggy, pepper, peter, phil, robbie, rosalind, ruby, samual, scott, sharon, stan, steve, sunil, tony, victoria, wanda])
db.session.commit()

# Make a bunch of competition rosters (men's soccer, men's football, men's/women's basketball, women's volleyball, women's dodgeball, spoken word)
tamu_m_soccer = Competition(school_code="tamu", comp_name="Men's Soccer", player=13)
# uh_m_football = Competition(school_code="uh", comp_name="Men's Football", captain=3, player=5)
# uta_m_basketball = Competition(comp_name="Men's Basketball")
tamu_w_basketball1 = Competition(school_code="tamu", comp_name="Women's Basketball", player=1)
tamu_w_basketball32 = Competition(school_code="tamu", comp_name="Women's Basketball", player=32)
tamu_w_basketball33 = Competition(school_code="tamu", comp_name="Women's Basketball", player=33)
# unt_w_volleyball = Competition(comp_name="Women's Volleyball")
# uta_w_dodgeball = Competition(comp_name="Women's Dodgeball")
# uta_k_bowl = Competition(comp_name="Knowledge Bowl")
# spoken_word = Competiton(comp_name="Spoken Word")

db.session.add_all([tamu_m_soccer, tamu_w_basketball1, tamu_w_basketball32, tamu_w_basketball33])
db.session.commit()
